### ISSUE TITLE
brain dump

### ISSUE THREAD

**Issue by duckinator** [how-is/dashboard#1]
Rails app

* generate a new report daily
* save the last 7 reports
* save any reports that land on a Sunday, for the last 4 Sundays
* save any reports that land on the 1st of a month, for the last 12 months
* save any reports that land on January 1st

Any reports not explicitly saved above can be removed at any point.

Homepage, for now, just dumps links to all reports. We'll want it to be paginated and have neat graphs and such at some point, but \~who cares\~ right now.

**Comment by indirect** [comment]
Perfect. 👍

**Comment by duckinator** [comment]
should also move the mockup elsewhere before nuking the existing sinatra app

**Comment by duckinator** [comment]
mockup moved to https://github.com/how-is/mockups/tree/master/dashboard, so it's okay to nuke the sinatra app.
