### ISSUE TITLE
track how_is version with reports

### ISSUE THREAD

**Issue by duckinator** [how-is/dashboard#6]
Idea: track the version of how_is used when generating each report, so certain features/graphs/etc of the dashboard can be flagged as requiring reports from a certain version of how_is.

E.g., if we add something like "average response time to new issues" in the future, trying to access that information from old reports will give an error. I'd feel more comfortable explicitly defining what a report can be expected to have than basically going through duck-typing hell to guess &mdash; assuming the lack of an item means it wasn't supported when that report is generated can lead to invalid reports (e.g. if how_is breaks for some reason) being interpreted awkwardly and screwing with the results.

Not sure if my idea is the best approach; basically just brain-dumping.

@indirect, thoughts?

**Comment by indirect** [comment]
@duckinator yeah, that's a super good idea. Worst case, we can use that to feature flag graphs or sections that depend on data from newer report versions.
